"""Ordered taxonomy rules for Juniper domain classification."""

from __future__ import annotations  # Keep annotations available for imported models.

from .models import DomainRule  # Share one immutable rule contract with the classifier.

GENERAL_DOMAIN = "juniper-general-reference"  # Use the contract fallback domain exactly.
SIGNAL_CONFIDENCE = {  # Rank signals so reports show how much evidence selected a domain.
    "title": 0.95,  # Trust titles first because they name the document purpose.
    "path": 0.90,  # Trust paths next because the harvester encodes subjects there.
    "category": 0.85,  # Trust categories when the source used a useful section.
    "heading": 0.75,  # Trust headings when front matter gives no clear signal.
    "content": 0.60,  # Treat body-only matches as weak because broad guides are noisy.
    "fallback": 0.20,  # Mark the required fallback as low confidence by design.
}
SIGNAL_ORDER = ("title", "path", "category", "heading", "content")  # State the scan order for every document.
SUBSTANTIAL_ONLY_DOMAINS = {  # Keep small fallback documents for the separate flyer grouping work.
    "juniper-aaa-radius-policy",  # Classify only substantial Steel-Belted Radius documents here.
    "juniper-legacy-security-management",  # Classify only substantial legacy security documents here.
    "juniper-mobile-packet-core",  # Classify only substantial MobileNext documents here.
    "juniper-network-management-platforms",  # Classify only substantial management platform documents here.
    "juniper-optical-transport",  # Classify only substantial packet optical documents here.
    "juniper-service-control-policy",  # Classify only substantial SRC and SDX documents here.
    "juniper-service-provider-planning",  # Classify only substantial planning documents here.
}
DOCUMENT_TYPE_RULES = (  # Apply required document-type rules before normal domain rules.
    DomainRule(1, "juniper-software-lifecycle", ("release notes",), ("release-notes",)),  # Keep releases in lifecycle.
    DomainRule(2, "juniper-security-srx-firewall", ("srx", "vsrx", "csrx")),  # Route SRX names to firewall first.
)
DOMAIN_RULES = (  # Preserve the priority table from contracts/domain-taxonomy.md.
    DomainRule(
        1,
        "juniper-cli-reference",
        ("junos cli reference", "cli reference", "command reference", "statement reference"),
        ("cli-reference",),
    ),
    DomainRule(
        2,
        "juniper-evpn-vxlan-fabric",
        (
            "evpn",
            "vxlan",
            "evpn-vxlan",
            "ip fabric",
            "spine",
            "leaf",
            "virtual chassis",
            "mc-lag",
            "mpls l2vpn",
            "layer 2 vpn",
            "vpls",
        ),
    ),
    DomainRule(
        3,
        "juniper-sdwan-wan",
        ("session smart", "sd-wan", "sdwan", "wan assurance", "wan edge", "128 technology", "conductor", "branch wan"),
        (),
        (r"\bssr\b",),
    ),
    DomainRule(
        4,
        "juniper-routing-policy-firewall",
        (
            "routing policy",
            "firewall filter",
            "traffic policer",
            "class of service",
            "policy framework",
            "route filter",
            "prefix list",
        ),
        (),
        (r"\bcos\b",),
    ),
    DomainRule(
        5,
        "juniper-api-automation",
        (
            "api",
            "rest",
            "netconf",
            "yang",
            "pyez",
            "grpc",
            "openflow",
            "ansible",
            "automation",
            "script",
            "sdk",
            "developer",
            "webhook",
            "telemetry",
        ),
        ("api",),
    ),
    DomainRule(
        6,
        "juniper-software-lifecycle",
        ("release notes", "upgrade", "update", "interim", "fix", "end of life", "end of support"),
        ("release-notes", "migration"),
        (r"\beol\b", r"\beos\b"),
    ),
    DomainRule(
        7,
        "juniper-security-analytics-compliance",
        (
            "jsa",
            "secure analytics",
            "security analytics",
            "siem",
            "log collector",
            "dsm",
            "fips",
            "common criteria",
            "fedramp",
            "compliance",
            "validation report",
        ),
        ("security-and-compliance",),
    ),
    DomainRule(
        8,
        "juniper-security-vpn-threat",
        ("ipsec", "vpn", "utm", "idp", "ips", "threat", "sky atp", "advanced threat", "secure edge"),
    ),
    DomainRule(
        9,
        "juniper-security-srx-firewall",
        ("srx", "vsrx", "csrx", "firewall", "nat", "security director", "security gateway"),
    ),
    DomainRule(10, "juniper-routing-director-operations", ("routing director",)),
    DomainRule(
        11,
        "juniper-observability-operations",
        (
            "paragon",
            "northstar",
            "healthbot",
            "monitor",
            "monitoring",
            "analytics",
            "insights",
            "planner",
            "orchestration",
            "proactive",
            "service assurance",
            "ai-scripts",
            "service now",
            "service insight",
        ),
    ),
    DomainRule(
        12,
        "juniper-network-management-platforms",
        (
            "junos space",
            "connectivity services director",
            "network director",
            "edge services director",
            "customer portal online help",
            "cloud customer portal",
            "cso",
            "atom user guide",
            "anuta atom",
            "junosv app engine",
            "junosphere",
        ),
    ),
    DomainRule(
        13,
        "juniper-subscriber-services",
        (
            "broadband subscriber",
            "subscriber management",
            "subscriber sessions",
            "bng",
            "aaa subscriber",
            "dynamic profiles",
            "pppoe",
            "dhcp subscriber",
        ),
    ),
    DomainRule(
        14,
        "juniper-mpls-transport",
        ("mpls", "ldp", "rsvp", "segment routing", "sr-mpls", "traffic engineering", "layer 3 vpn", "l3vpn"),
    ),
    DomainRule(
        15,
        "juniper-routing-protocols",
        (
            "bgp",
            "ospf",
            "isis",
            "is-is",
            "rip",
            "route reflection",
            "multicast",
            "pim",
            "igmp",
            "msdp",
            "routing protocol",
        ),
    ),
    DomainRule(
        16,
        "juniper-junos-fundamentals",
        (
            "beginner's guide to learning junos",
            "junos os cli user guide",
            "cli user guide",
            "cli basics",
            "configuration mode",
            "configuration hierarchy",
            "first-time setup",
            "high availability user guide",
            "multinode high availability",
            "timing and synchronization",
            "continuity software",
            "commit",
            "rollback",
            "system services",
            "user management",
            "authentication",
            "routing engine",
            "chassis cluster",
            "interfaces",
            "licensing guide",
            "standards reference",
        ),
    ),
    DomainRule(
        17,
        "juniper-datacenter-switching",
        (
            "qfx",
            "qfabric",
            "complete software guide for junos os for the qfx",
            "traffic management on the qfx",
            "storage on the qfx",
            "routing options on the qfx",
            "security on the qfx",
            "user and access management on the qfx",
            "high availability features on the qfx",
        ),
        (),
        (r"\bqfx\d+\b",),
    ),
    DomainRule(
        18, "juniper-datacenter-apstra", ("apstra", "data center", "datacenter", "intent-based", "sfs", "smart fabric")
    ),
    DomainRule(
        19,
        "juniper-cloud-native-contrail",
        (
            "contrail",
            "cloud native",
            "cloud-native",
            "cn2",
            "kubernetes",
            "openshift",
            "containerized",
            "cni",
            "virtual network",
        ),
    ),
    DomainRule(
        20,
        "juniper-mist-ai-cloud",
        (
            "mist",
            "marvis",
            "ai-native",
            "assurance",
            "premium analytics",
            "wi-fi",
            "wlan",
            "access point",
            "ble",
            "radio",
            "antenna",
            "location services",
            "wireless assessment",
            "wireless location",
        ),
        (),
        (r"\bap\d+\b",),
    ),
    DomainRule(
        21,
        "juniper-mobile-packet-core",
        (
            "mobilenext",
            "mobile next",
            "broadband gateway",
            "pdn gateway",
            "p-gw",
            "s-gw",
            "ggsn",
            "pcef",
            "mobile gateway",
            "charging for serving gateway",
            "config-guide-mobility",
            "juniper-mbg",
            "swcmdref-mobility",
            "statements and commands reference guide",
            "serving gateway",
            "gprs tunneling protocol",
            "redundancy",
            "system architecture",
            "network architecture",
            "exception handling",
        ),
    ),
    DomainRule(
        22,
        "juniper-aaa-radius-policy",
        ("steel-belted", "steel belted", "radius carrier", "funk steel-belted radius"),
    ),
    DomainRule(
        23,
        "juniper-service-control-policy",
        (
            "session and resource control",
            "src pe",
            "src cli",
            "src-pe",
            "sdx",
            "application library guide",
            "subscribers and subscriptions guide",
            "services and policies guide",
        ),
        (),
        (r"\bsrc\b",),
    ),
    DomainRule(
        24,
        "juniper-optical-transport",
        (
            "bti7000",
            "bti7800",
            "tl1 reference",
            "packetvx",
            "ctpview",
            "ctp series",
            "tcx series",
            "optical transport",
        ),
    ),
    DomainRule(
        25,
        "juniper-legacy-security-management",
        (
            "network and security manager",
            "network security manager",
            "nsm",
            "screenos",
            "firefly host",
            "firefly perimeter",
            "vgw series",
            "webapp secure",
            "mykonos",
            "strm",
            "netscreen",
            "isg 2000",
            "corero smartwall",
            "juniper atp appliance",
            "secintel",
            "policy enforcer",
            "application layer gateways",
            "attack detection",
            "public key infrastructure",
            "hardening junos devices",
        ),
    ),
    DomainRule(
        26,
        "juniper-service-provider-planning",
        ("ip/mplsview", "ip-mplsview", "wandl", "proactive services", "packet walkthrough", "junos fusion"),
    ),
    DomainRule(
        27,
        "juniper-campus-branch-switching",
        (
            "campus",
            "branch",
            "switching",
            "switches",
            "switch",
            "ethernet switch",
            "wired access",
            "spanning-tree",
            "spanning tree",
            "poe",
        ),
        (),
        (r"\bex\d+\b",),
    ),
    DomainRule(
        28,
        "juniper-hardware-platforms",
        (
            "datasheet",
            "data sheet",
            "hardware",
            "platform",
            "hwguide",
            "hw guide",
            "chassis",
            "line card",
            "mic",
            "pic",
            "fpc",
            "transceiver",
            "power supply",
            "fan tray",
            "module",
            "adapter",
            "optics",
            "cable",
            "m20",
            "m40",
            "m160",
        ),
        ("datasheets",),
    ),
    DomainRule(
        29,
        "juniper-installation-maintenance",
        ("installation", "install", "rack", "mount", "cabling", "replacement", "fru", "maintenance"),
        ("installation-guides", "configuration-guides", "administration-guides"),
    ),
    DomainRule(
        30,
        "juniper-training-learning",
        (
            "day one",
            "dayone",
            "getting started",
            "quick start",
            "quickstart",
            "lab",
            "learning",
            "certification",
            "exam",
            "student",
            "course",
        ),
    ),
    DomainRule(
        31,
        "juniper-business-solutions",
        (
            "case study",
            "solution brief",
            "white paper",
            "analyst report",
            "customer story",
            "industry",
        ),
        (
            "case-studies",
            "solution-briefs",
            "white-papers",
            "flyers",
            "infographics",
            "analyst-reports",
            "ebooks",
            "executive-briefs",
            "use-cases",
            "brochures",
            "factsheet",
            "editorials",
            "articles",
            "marketing-asset",
            "reference-architectures",
            "validation-reports",
            "design",
        ),
    ),
    DomainRule(
        32,
        "juniper-legal-corporate",
        (
            "anti-corruption",
            "code of conduct",
            "trademark",
            "privacy",
            "personal data",
            "conflict minerals",
            "accessibility",
            "esg",
            "cdp",
            "certificate",
        ),
        ("legal", "sustainability", "certificates", "service-descriptions"),
    ),
)
